### ISSUE TITLE
goTo / goToPassage

### ISSUE THREAD

**Issue by jasontaylor579** [massivedanger/protagonist#6]
(Edited to reflect further research): Not sure if this is a documentation or functional issue or both... story.goToPassage and goTo (which seem equivalent but one requires the object and one is just a helper?) both seem to return a blank passage instead of my specified passage. Tried it with %= and just plain old % and also tried referring to passage by name and by number and even by story.startPassageID!

Anyway, a bit of clarity on whether these functions are supposed to immediately jump the player to the named passage (with no link click required) or somehow incorporate the passage or do something else entirely would be a big help... not entirely sure if there is also a bug here, but I think I've tried about every possible syntactical combination without getting any expected results...

**Comment by evanwalsh** [comment]
@jasontaylor579 I'm sorry you're having trouble! It should be forwarding the player directly to the passage without any intervention on their part. I'll look into it and get back to you soon.
