### ISSUE TITLE
"Add a New Format" Error

### ISSUE THREAD

**Issue by callym** [massivedanger/protagonist#9]
When trying to use the new link, got this error:
`The story format at https://raw.githubusercontent.com/massivedanger/protagonist/master/dist/format.js could not be added (Story format source did not call window.storyFormat()).`

**Comment by hoverbird** [comment]
I'm getting the same error, even when adding the exact same version I've successfully added in the past. Perhaps this broke in a recent Twine update?

**Comment by evanwalsh** [comment]
@callym @hoverbird Sorry for taking so long on this! I need better notifications for this repo.

The format works if you use Twine 2.0.9pre1 ([available here](https://bitbucket.org/klembot/twinejs/downloads/)) and [the new link for the format](https://cdn.rawgit.com/massivedanger/protagonist/master/dist/format.js), which I just added to the README for posterity.

Let me know if that works!

**Comment by evanwalsh** [comment]
This is, apparently, fixed.
